### PR TITLE
Update dependencies to fix known vulnerabilities

### PR DESCRIPTION
**Pull request by hthetiot**
- https://snyk.io/test/npm/phantom-wd/0.0.2

### CODE REVIEW

**Comment by hthetiot** [comment]
Hello @Stuk Would you allow me to contribute to phantom-wd please.
I would need npm list publish right and github right.
Thanks.

**Comment by Stuk** [comment]
I've added you as a contributor to phantom-wd on npm!

**Comment by hthetiot** [comment]
@Stuk many thanks \o/

**Comment by hthetiot** [comment]
@Stuk just published 0.0.3 on npm.
- https://www.npmjs.com/package/phantom-wd

Could you give me right to git tag "0.0.3" on master in this repository.

Finally here is the new security check after merge.

Before:
screen shot 2017-05-10 at 1 13 45 am

After:
screen shot 2017-05-10 at 1 13 36 am

**Comment by Stuk** [comment]
I've added you as a collaborator, so you should be able to push the tag now

**Comment by hthetiot** [comment]
@Stuk Thanks so much.

**Pull request merged**
